import Head from 'next/head'
import { Inter } from '@next/font/google'
import Nav from '../components/Nav'
import Vid from '../components/Video'
import Discrip from '../components/discription'
import Feature from '../components/feature'
import Technology from '../components/technology';
import Addhere from '../components/adhere'
import Sign from '../components/signin'
import Footer from '../components/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Product Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      
      </Head>
      <div className="bg-black">
     <Nav />
     <Vid />
     <Discrip />
     <Feature />
     <Technology />
     <Addhere />
     <Sign />
     <Footer />
      </div>
    </>
  )
}
